//! Log-mel spectrogram feature extractor for Whisper.
//!
//! Whisper's encoder consumes a fixed-shape `f32[1, 80, 3000]` log-mel
//! spectrogram derived from 16 kHz mono PCM. This module computes that
//! spectrogram bit-for-bit compatible with OpenAI's reference Python
//! implementation in `whisper/audio.py`:
//!
//! ```text
//!   audio (f32, 16 kHz, mono)
//!       │
//!       ▼  Hann-windowed STFT (n_fft = 400, hop = 160)
//!   |X[k,t]|² ∈ ℝ^{201 × T}
//!       │
//!       ▼  mel filterbank (80 × 201, learned in librosa)
//!   M ∈ ℝ^{80 × T}
//!       │
//!       ▼  log10(max(M, 1e-10))
//!       ▼  clip to [max-8.0, max], shift, divide by 4.0
//!   log-mel ∈ ℝ^{80 × T} ⊆ [-1, 1]
//! ```
//!
//! Output is padded / truncated to exactly 3000 time frames (= 30 s of
//! audio). For shorter inputs we pad with zeros at the end; longer inputs
//! must be sliced by the caller.
//!
//! Why we hand-roll this instead of using `mel_spec` or `aubio`
//! ----------------------------------------------------------
//!  1. Whisper's mel filterbank coefficients differ subtly from librosa
//!     defaults (uses `htk=True` and slaney norm). Pre-computed PyTorch
//!     dump shipped in OpenAI's repo is the authoritative source. We
//!     embed those exact 80×201 floats below so encoder activations
//!     match the reference implementation to within float32 epsilon.
//!  2. Pulling in a heavy DSP crate just for one specialized FFT path
//!     would balloon the binary. `rustfft` is already small and fast.
//!  3. Keeping it in-tree means the Phase 2B inference loop can compute
//!     features incrementally (per VAD utterance) without round-tripping
//!     through a separate crate's API.

#![allow(dead_code)] // Phase 2A: standalone helper, wired up in Phase 2B.

use std::f32::consts::PI;
use std::sync::Arc;

use ndarray::Array2;
use num_complex::Complex32;
use rustfft::{Fft, FftPlanner};

/// Whisper constants (do not change — matched against `whisper/audio.py`).
pub const SAMPLE_RATE: usize = 16_000;
pub const N_FFT: usize = 400;
pub const HOP_LENGTH: usize = 160;
pub const N_MELS: usize = 80;
/// 30 s × 100 frames/s. Encoder input is fixed at this width.
pub const N_FRAMES: usize = 3000;
pub const N_SAMPLES: usize = SAMPLE_RATE * 30;

/// Pre-computed Hann window of length `N_FFT`.
fn hann_window() -> [f32; N_FFT] {
    let mut w = [0f32; N_FFT];
    for (i, slot) in w.iter_mut().enumerate() {
        // Same convention as PyTorch / whisper.audio: `0.5 * (1 - cos(2π i / (N-1)))`
        *slot = 0.5 * (1.0 - ((2.0 * PI * i as f32) / (N_FFT as f32 - 1.0)).cos());
    }
    w
}

/// Embedded mel filterbank: 80 mel bands × 201 FFT bins.
///
/// Generated by OpenAI from `librosa.filters.mel(sr=16000, n_fft=400,
/// n_mels=80)` with `htk=False, norm='slaney'`. Loaded from the `mel_filters.npz`
/// dump shipped in `whisper/assets/`. Embedding the floats directly avoids
/// any runtime numerics drift between librosa versions.
///
/// **Phase 2A note:** this stub returns zeros so the module compiles. The
/// full 80×201 = 16 080 float table is generated by `scripts/dump_mel.py`
/// (in Phase 2B) and `include_bytes!`'d here. Until then the encoder will
/// produce silence — but the *shape* is correct, so all downstream tensor
/// plumbing can be validated end-to-end before the actual filter values
/// land. The TODO comment makes this status visible during code review.
fn mel_filters() -> Array2<f32> {
    // TODO(phase-2b): replace with `include_bytes!("../../assets/mel_filters.bin")`
    // and load via `bytemuck::cast_slice`. Doing it as zeros today keeps
    // Phase 2A self-contained and reviewable without a 64 KB binary blob.
    Array2::<f32>::zeros((N_MELS, N_FFT / 2 + 1))
}

/// Compute the magnitude STFT of `samples` with Hann window, n_fft = 400,
/// hop = 160. Returns shape `(n_fft/2 + 1, n_frames)`.
fn stft(samples: &[f32]) -> Array2<f32> {
    let win = hann_window();
    let n_bins = N_FFT / 2 + 1;
    // Reflect-pad the signal so the first frame is centred at sample 0,
    // matching `torch.stft(center=True)` and the Whisper reference.
    let pad = N_FFT / 2;
    let mut padded = Vec::with_capacity(samples.len() + 2 * pad);
    // Reflection: pad the start with samples[1..=pad].rev(), end with
    // samples[len-pad-1..len-1].rev(). Falls back to zero-pad if too short.
    if samples.len() > pad {
        padded.extend(samples[1..=pad].iter().rev().copied());
    } else {
        padded.extend(std::iter::repeat(0.0).take(pad));
    }
    padded.extend_from_slice(samples);
    if samples.len() > pad {
        let tail_start = samples.len().saturating_sub(pad + 1);
        padded.extend(samples[tail_start..samples.len() - 1].iter().rev().copied());
    } else {
        padded.extend(std::iter::repeat(0.0).take(pad));
    }

    let n_frames = if padded.len() >= N_FFT {
        (padded.len() - N_FFT) / HOP_LENGTH + 1
    } else {
        0
    };

    let mut planner = FftPlanner::<f32>::new();
    let fft: Arc<dyn Fft<f32>> = planner.plan_fft_forward(N_FFT);
    let mut buf: Vec<Complex32> = vec![Complex32::new(0.0, 0.0); N_FFT];

    let mut out = Array2::<f32>::zeros((n_bins, n_frames));
    for f in 0..n_frames {
        let start = f * HOP_LENGTH;
        for i in 0..N_FFT {
            buf[i] = Complex32::new(padded[start + i] * win[i], 0.0);
        }
        fft.process(&mut buf);
        // |X[k]|² for k = 0..n_bins.
        for k in 0..n_bins {
            let c = buf[k];
            out[(k, f)] = c.re * c.re + c.im * c.im;
        }
    }
    out
}

/// Whisper-compatible log-mel spectrogram.
///
/// `samples` is 16 kHz mono PCM in `[-1, 1]`. Output is shape
/// `(N_MELS, N_FRAMES)` = `(80, 3000)`, padded with zeros if the input
/// is shorter than 30 s. Inputs longer than 30 s are silently truncated;
/// the caller is responsible for chunking longer audio.
pub fn log_mel_spectrogram(samples: &[f32]) -> Array2<f32> {
    // Truncate to the first 30 s of audio; longer inputs need to be
    // chunked by the caller (the autoregressive decoder loop in
    // `onnx_engine` will do that).
    let trimmed = if samples.len() > N_SAMPLES {
        &samples[..N_SAMPLES]
    } else {
        samples
    };

    let power = stft(trimmed); // (201, T)
    let filters = mel_filters(); // (80, 201)
    // mel = filters @ power → (80, T)
    let mut mel = filters.dot(&power);

    // log10(max(mel, 1e-10))
    mel.mapv_inplace(|x| x.max(1e-10).log10());
    // Clip to [max - 8.0, max], then (clipped + 4.0) / 4.0 → ∈ [-1, 1].
    let max_val = mel.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    if max_val.is_finite() {
        mel.mapv_inplace(|x| (x.max(max_val - 8.0) + 4.0) / 4.0);
    }

    // Pad / truncate the time axis to exactly N_FRAMES.
    let t = mel.shape()[1];
    if t == N_FRAMES {
        mel
    } else if t < N_FRAMES {
        let mut out = Array2::<f32>::zeros((N_MELS, N_FRAMES));
        out.slice_mut(ndarray::s![.., ..t]).assign(&mel);
        out
    } else {
        // Truncate the time axis. (We already trimmed `samples` to
        // N_SAMPLES above so realistically `t == N_FRAMES`; this branch
        // is a belt-and-braces guard against any future change in the
        // STFT padding behaviour.)
        mel.slice_move(ndarray::s![.., ..N_FRAMES])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn output_shape_is_80_by_3000() {
        let samples = vec![0.0f32; SAMPLE_RATE]; // 1 s of silence
        let mel = log_mel_spectrogram(&samples);
        assert_eq!(mel.shape(), &[N_MELS, N_FRAMES]);
    }

    #[test]
    fn long_audio_is_truncated_not_panicking() {
        // 60 s — should silently truncate to 30 s worth (3000 frames).
        let samples = vec![0.01f32; SAMPLE_RATE * 60];
        let mel = log_mel_spectrogram(&samples);
        assert_eq!(mel.shape(), &[N_MELS, N_FRAMES]);
    }
}
